server:
  port: 8083

spring:
  application:
    name: delivery-service

  data:
    mongodb:
      uri: mongodb://admin:adminpassword@localhost:27017/delivery_service?authSource=admin

  cloud:
    function:
      definition: deliveryCommandsConsumer
    stream:
      bindings:
        deliveryCommandsConsumer-in-0:
          destination: delivery.commands
          group: delivery-service
          contentType: application/json
          consumer:
            maxAttempts: 3
            backOffInitialInterval: 1000
            backOffMultiplier: 2.0
            backOffMaxInterval: 10000
            concurrency: 3
        deliveryResults-out-0:
          destination: delivery.events
          contentType: application/json
      kafka:
        binder:
          brokers: localhost:9092
        bindings:
          deliveryCommandsConsumer-in-0:
            consumer:
              enableDlq: true
              configuration:
                key.deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
                value.deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
                auto.offset.reset: earliest
          deliveryResults-out-0:
            producer:
              configuration:
                key.serializer: org.apache.kafka.common.serialization.ByteArraySerializer
                value.serializer: org.apache.kafka.common.serialization.ByteArraySerializer

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      probes:
        enabled: true
  health:
    defaults:
      enabled: true

logging:
  level:
    root: INFO
    it.vnuzzo: INFO
    org.springframework.cloud.stream: INFO
    org.springframework.kafka: WARN
    org.springframework.data.mongodb: WARN

app:
  web-client:
    recipient:
      base-url: http://localhost:8081
      uri: api/recipients/validate
      timeout: 30000
      connection-timeout: 30000
      response-timeout: 30000
    document:
      base-url: http://localhost:8085
      uri: /documents/validate
      timeout: 30000
      connection-timeout: 30000
      response-timeout: 30000
  delivery:
    consumer-name: delivery-service:delivery.commands